namespace Game.Editor.UberEnums
{
    using System;
    using System.Text;
    using UnityCodeGen;
    using UnityEditor;
    using UnityEngine;

    [Generator]
    public class UberEnumGenerator : ICodeGenerator
    {
        public void Execute(GeneratorContext context)
        {
            var config = ScriptableSingleton<UberEnumConfig>.instance;
            if (config == null || string.IsNullOrEmpty(config.currentIndex))
            {
                return;
            }

            var data = config[config.currentIndex];
            if (data == null)
            {
                ClearCurrentIndex(config);
                return;
            }

            if (!UberEnumApi.TryValidateEnumData(data, out var error))
            {
                Debug.LogError(error);
                ClearCurrentIndex(config);
                return;
            }

            var name = UberEnumApi.NormalizeIdentifier(data.name);

            context.OverrideFolderPath(data.path);
            var sb = new StringBuilder();
            sb.AppendLine(@"// <auto-generated/>");
            sb.AppendLine($"namespace {data.@namespace}");
            sb.AppendLine("{");
            sb.AppendLine("\tusing System;");
            if (data.isFlags)
            {
                sb.AppendLine("\t[Flags]");
            }

            sb.AppendLine($"\tpublic enum {name}");
            sb.AppendLine("\t{");
            for (int i = 0; i < data.values.Length; i++)
            {
                var entry = data.values[i];
                var value = data.isFlags ? $"1 << {entry.value}" : entry.value.ToString();
                sb.AppendLine($"\t\t{UberEnumApi.NormalizeIdentifier(entry.name)} = {value},");
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");
            context.AddCode($"{name}.cs", sb.ToString());
        }

        private static void ClearCurrentIndex(UberEnumConfig config)
        {
            config.currentIndex = string.Empty;
            config.SaveConfig();
        }
    }
}